# Generated by Django 5.2.5 on 2025-09-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='settings/', verbose_name='Logo')),
                ('slogan', models.CharField(max_length=60, verbose_name='Slogan')),
                ('perfect_bodies_num', models.CharField(max_length=4, verbose_name='Number of Perfect Bodies')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_slogan', models.CharField(max_length=60, verbose_name='Footer Slogan')),
                ('footer_image', models.ImageField(upload_to='settings/', verbose_name='Footer Image')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_footer', to='settings.info')),
            ],
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_title', models.CharField(max_length=30, verbose_name='Brief Title')),
                ('brief_content', models.CharField(max_length=100, verbose_name='Brief')),
                ('brief_image', models.ImageField(upload_to='settings/', verbose_name='Brief Image')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_brief', to='settings.info')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_content', models.CharField(max_length=100, verbose_name='About Us')),
                ('about_us_image', models.ImageField(upload_to='settings/', verbose_name='About US Image')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_about_us', to='settings.info')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField(blank=True, max_length=100, verbose_name='Youtube Link')),
                ('whatsapp', models.URLField(blank=True, max_length=100, verbose_name='Whatsapp Link')),
                ('facebook', models.URLField(blank=True, max_length=100, verbose_name='Facebook Link')),
                ('instagram', models.URLField(blank=True, max_length=100, verbose_name='Instagram Link')),
                ('tiktok', models.URLField(blank=True, max_length=100, verbose_name='Tiktok Link')),
                ('telegram', models.URLField(blank=True, max_length=100, verbose_name='Telegram Link')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_links', to='settings.info')),
            ],
        ),
    ]
