# Generated by Django 5.2.5 on 2025-10-25 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='settings/', verbose_name='Logo')),
                ('slogan', models.CharField(max_length=200, verbose_name='Slogan')),
                ('slogan_ar', models.CharField(max_length=200, null=True, verbose_name='Slogan')),
                ('slogan_en', models.CharField(max_length=200, null=True, verbose_name='Slogan')),
            ],
        ),
        migrations.CreateModel(
            name='PackadgeAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantages', models.TextField(verbose_name='Pack Advantages')),
                ('advantages_ar', models.TextField(null=True, verbose_name='Pack Advantages')),
                ('advantages_en', models.TextField(null=True, verbose_name='Pack Advantages')),
            ],
        ),
        migrations.CreateModel(
            name='PackadgeDisadvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disadvantages', models.TextField(verbose_name='Pack Disadvantages')),
                ('disadvantages_ar', models.TextField(null=True, verbose_name='Pack Disadvantages')),
                ('disadvantages_en', models.TextField(null=True, verbose_name='Pack Disadvantages')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfullStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('before_image', models.ImageField(upload_to='settings/', verbose_name='Before Image')),
                ('after_image', models.ImageField(upload_to='settings/', verbose_name='After Image')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_slogan', models.CharField(max_length=200, verbose_name='Footer Slogan')),
                ('footer_image', models.ImageField(upload_to='settings/', verbose_name='Footer Image')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_footer', to='settings.info')),
            ],
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_title', models.CharField(max_length=100, verbose_name='Brief Title')),
                ('brief_title_ar', models.CharField(max_length=100, null=True, verbose_name='Brief Title')),
                ('brief_title_en', models.CharField(max_length=100, null=True, verbose_name='Brief Title')),
                ('brief_content', models.TextField(verbose_name='Brief')),
                ('brief_content_ar', models.TextField(null=True, verbose_name='Brief')),
                ('brief_content_en', models.TextField(null=True, verbose_name='Brief')),
                ('brief_image', models.ImageField(upload_to='settings/', verbose_name='Brief Image')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_brief', to='settings.info')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_content', models.TextField(verbose_name='About Us')),
                ('about_us_content_ar', models.TextField(null=True, verbose_name='About Us')),
                ('about_us_content_en', models.TextField(null=True, verbose_name='About Us')),
                ('about_us_image', models.ImageField(upload_to='settings/', verbose_name='About US Image')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_about_us', to='settings.info')),
            ],
        ),
        migrations.CreateModel(
            name='Packadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Packadge')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='Packadge')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Packadge')),
                ('before_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.CharField(max_length=100, verbose_name='Duration')),
                ('time_ar', models.CharField(max_length=100, null=True, verbose_name='Duration')),
                ('time_en', models.CharField(max_length=100, null=True, verbose_name='Duration')),
                ('image', models.ImageField(upload_to='settings/', verbose_name='Packadge Image')),
                ('advantages', models.ManyToManyField(blank=True, null=True, related_name='packadge_pros', to='settings.packadgeadvantage')),
                ('disadvantages', models.ManyToManyField(blank=True, null=True, related_name='packadge_cons', to='settings.packadgedisadvantage')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField(blank=True, max_length=100, verbose_name='Youtube Link')),
                ('whatsapp', models.URLField(blank=True, max_length=100, verbose_name='Whatsapp Link')),
                ('facebook', models.URLField(blank=True, max_length=100, verbose_name='Facebook Link')),
                ('instagram', models.URLField(blank=True, max_length=100, verbose_name='Instagram Link')),
                ('instagram_page', models.URLField(blank=True, max_length=100, verbose_name='Instagram Page Link')),
                ('tiktok', models.URLField(blank=True, max_length=100, verbose_name='Tiktok Link')),
                ('telegram', models.URLField(blank=True, max_length=100, verbose_name='Telegram Link')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_links', to='settings.info')),
            ],
        ),
    ]
