# Generated by Django 5.2.6 on 2026-07-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='home',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='home',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='home',
        ),
        migrations.RemoveField(
            model_name='sociallinks',
            name='home',
        ),
    ]
