# Generated by Django 5.2.5 on 2025-09-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='perfect_bodies_num',
        ),
    ]
