# Generated by Django 5.2.5 on 2025-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_info_perfect_bodies_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='brief_end',
            field=models.CharField(default=1, max_length=100, verbose_name='Brief End'),
            preserve_default=False,
        ),
    ]
