# Generated by Django 5.2.6 on 2026-07-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_aboutus_home_remove_brief_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_slogan_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Footer Slogan'),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_slogan_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Footer Slogan'),
        ),
    ]
