# Generated by Django 5.2.6 on 2026-07-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_footer_footer_slogan_ar_footer_footer_slogan_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packadges',
            name='advantages',
            field=models.ManyToManyField(blank=True, related_name='packadge_pros', to='settings.packadgeadvantage'),
        ),
        migrations.AlterField(
            model_name='packadges',
            name='disadvantages',
            field=models.ManyToManyField(blank=True, related_name='packadge_cons', to='settings.packadgedisadvantage'),
        ),
    ]
