# Generated by Django 5.2.5 on 2025-09-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_brief_brief_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_us_content',
            field=models.CharField(verbose_name='About Us'),
        ),
    ]
