# Generated by Django 5.2.5 on 2025-09-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_aboutus_about_us_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_us_content',
            field=models.TextField(verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='brief_content',
            field=models.TextField(max_length=100, verbose_name='Brief'),
        ),
    ]
