# Generated by Django 5.2.6 on 2026-07-11 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_packadges_advantages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Feature')),
                ('text_ar', models.TextField(null=True, verbose_name='Feature')),
                ('text_en', models.TextField(null=True, verbose_name='Feature')),
            ],
        ),
        migrations.RemoveField(
            model_name='packadges',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='packadges',
            name='disadvantages',
        ),
        migrations.CreateModel(
            name='PackadgeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True, verbose_name='Included in this package?')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.feature')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.packadges')),
            ],
            options={
                'unique_together': {('package', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='packadges',
            name='features',
            field=models.ManyToManyField(related_name='packages', through='settings.PackadgeFeature', to='settings.feature'),
        ),
        migrations.DeleteModel(
            name='PackadgeAdvantage',
        ),
        migrations.DeleteModel(
            name='PackadgeDisadvantage',
        ),
    ]
