# Generated by Django 5.2.5 on 2025-09-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_aboutus_about_us_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='brief_end',
        ),
    ]
