# Generated by Django 5.2.6 on 2026-07-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_feature_remove_packadges_advantages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packadgefeature',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='packadgefeature',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
