# Generated by Django 5.2.5 on 2025-09-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_brief_brief_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='brief_content',
            field=models.TextField(verbose_name='Brief'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='brief_title',
            field=models.CharField(max_length=100, verbose_name='Brief Title'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_slogan',
            field=models.CharField(max_length=200, verbose_name='Footer Slogan'),
        ),
        migrations.AlterField(
            model_name='info',
            name='slogan',
            field=models.CharField(max_length=200, verbose_name='Slogan'),
        ),
    ]
