# Generated by Django 5.2.6 on 2026-07-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_packadgefeature_options_packadgefeature_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
