# Generated by Django 5.2.5 on 2025-09-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_brief_brief_content_alter_brief_brief_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='instagram_page',
            field=models.URLField(blank=True, max_length=100, verbose_name='Instagram Page Link'),
        ),
    ]
