# Generated by Django 5.2.6 on 2026-07-11 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_delete_footer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackadgeFeature',
            new_name='PackageFeature',
        ),

        migrations.RenameModel(
            old_name='Packadges',
            new_name='Packages',
        ),
        
        migrations.AlterField(
            model_name='packagefeature',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.packages'),
        ),
        
    ]
