# Generated by Django 5.2.5 on 2025-09-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_sociallinks_instagram_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfullStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('before_image', models.ImageField(upload_to='settings/', verbose_name='Before Image')),
                ('after_image', models.ImageField(upload_to='settings/', verbose_name='After Image')),
            ],
        ),
    ]
