# Generated by Django 5.2.6 on 2026-07-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_rename_packadgefeature_packagefeature_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=models.ImageField(upload_to='settings/', verbose_name='Package Image'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Package'),
        ),
    ]
