# Generated by Django 5.2.5 on 2025-09-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_successfullstories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Packadge')),
                ('before_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.CharField(max_length=100, verbose_name='Duration')),
                ('image', models.ImageField(upload_to='settings/', verbose_name='Packadge Image')),
            ],
        ),
        migrations.CreateModel(
            name='PackadgeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantages', models.TextField(verbose_name='Pack Advantages')),
                ('disadvantages', models.TextField(verbose_name='Pack Disadvantages')),
                ('packadge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packadge_details', to='settings.packadges', verbose_name='Packadge')),
            ],
        ),
    ]
