# Generated by Django 5.2.5 on 2025-09-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_packadges_packadgedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackadgeAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantages', models.TextField(verbose_name='Pack Advantages')),
                ('packadge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packadge_pros', to='settings.packadges', verbose_name='Packadge')),
            ],
        ),
        migrations.CreateModel(
            name='PackadgeDisadvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disadvantages', models.TextField(verbose_name='Pack Disadvantages')),
                ('packadge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packadge_cons', to='settings.packadges', verbose_name='Packadge')),
            ],
        ),
        migrations.DeleteModel(
            name='PackadgeDetails',
        ),
    ]
