# Generated by Django 5.2.5 on 2025-09-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_packadgeadvantage_packadgedisadvantage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packadgeadvantage',
            name='packadge',
        ),
        migrations.RemoveField(
            model_name='packadgedisadvantage',
            name='packadge',
        ),
        migrations.AddField(
            model_name='packadges',
            name='advantages',
            field=models.ManyToManyField(blank=True, null=True, related_name='packadge_pros', to='settings.packadgeadvantage'),
        ),
        migrations.AddField(
            model_name='packadges',
            name='disadvantages',
            field=models.ManyToManyField(blank=True, null=True, related_name='packadge_cons', to='settings.packadgedisadvantage'),
        ),
    ]
