# Generated by Django 5.2.5 on 2025-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_remove_packadgeadvantage_packadge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_us_content_ar',
            field=models.TextField(null=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_us_content_en',
            field=models.TextField(null=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='brief',
            name='brief_content_ar',
            field=models.TextField(null=True, verbose_name='Brief'),
        ),
        migrations.AddField(
            model_name='brief',
            name='brief_content_en',
            field=models.TextField(null=True, verbose_name='Brief'),
        ),
        migrations.AddField(
            model_name='brief',
            name='brief_title_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Brief Title'),
        ),
        migrations.AddField(
            model_name='brief',
            name='brief_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Brief Title'),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_slogan_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Footer Slogan'),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_slogan_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Footer Slogan'),
        ),
        migrations.AddField(
            model_name='info',
            name='slogan_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='info',
            name='slogan_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='packadgeadvantage',
            name='advantages_ar',
            field=models.TextField(null=True, verbose_name='Pack Advantages'),
        ),
        migrations.AddField(
            model_name='packadgeadvantage',
            name='advantages_en',
            field=models.TextField(null=True, verbose_name='Pack Advantages'),
        ),
        migrations.AddField(
            model_name='packadgedisadvantage',
            name='disadvantages_ar',
            field=models.TextField(null=True, verbose_name='Pack Disadvantages'),
        ),
        migrations.AddField(
            model_name='packadgedisadvantage',
            name='disadvantages_en',
            field=models.TextField(null=True, verbose_name='Pack Disadvantages'),
        ),
        migrations.AddField(
            model_name='packadges',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Packadge'),
        ),
        migrations.AddField(
            model_name='packadges',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Packadge'),
        ),
        migrations.AddField(
            model_name='packadges',
            name='time_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='packadges',
            name='time_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='successfullstories',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='successfullstories',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
