# Generated by Django 5.2.5 on 2025-09-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_aboutus_about_us_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successfullstories',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='successfullstories',
            name='name_en',
        ),
    ]
