# Generated by Django 5.2.5 on 2025-10-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_remove_successfullstories_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='footer_slogan_ar',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_slogan_en',
        ),
    ]
