# Generated by Django 5.2.5 on 2025-10-25 12:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Join Date')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Height (cm)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (kg)')),
                ('weight_measure_date', models.DateField(default=datetime.date.today, verbose_name='Weight Measurement Date')),
                ('whatsapp_number', models.CharField(max_length=13, verbose_name='Whatsapp Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram User')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6, verbose_name='Gender')),
                ('education', models.CharField(max_length=150, verbose_name='Education')),
                ('sizes', models.TextField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], max_length=9, verbose_name='Plan')),
                ('recommend_us', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Recommend us')),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate_name', models.CharField(choices=[('Alexandria', 'Alexandria'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Beheira', 'Beheira'), ('Beni Suef', 'Beni Suef'), ('Cairo', 'Cairo'), ('Dakahlia', 'Dakahlia'), ('Damietta', 'Damietta'), ('Faiyum', 'Faiyum'), ('Gharbia', 'Gharbia'), ('Giza', 'Giza'), ('Ismailia', 'Ismailia'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Luxor', 'Luxor'), ('Matruh', 'Matruh'), ('Minya', 'Minya'), ('Monufia', 'Monufia'), ('New Valley', 'New Valley (Wadi El Gedid)'), ('North Sinai', 'North Sinai'), ('Port Said', 'Port Said'), ('Qalyubia', 'Qalyubia'), ('Qena', 'Qena'), ('Red Sea', 'Red Sea'), ('Sharqia', 'Sharqia'), ('Sohag', 'Sohag'), ('South Sinai', 'South Sinai'), ('Suez', 'Suez')], max_length=30, verbose_name='Governrate name')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals_num', models.CharField(choices=[('A MEAL', 'A meal'), ('2 MEALS', '2 meals'), ('3 MEALS', '3 meals'), ('4 MEALS', '4 meals'), ('5 MEALS', '5 meals')], max_length=7, verbose_name='Meals number')),
                ('training_type', models.CharField(choices=[('GYM', 'Gym'), ('HOME', 'Home')], max_length=4, verbose_name='Gym or home')),
                ('workout_days', models.CharField(choices=[('A DAY', 'A day'), ('2 DAYS', '2 days'), ('3 DAYS', '3 days'), ('4 DAYS', '4 days'), ('5 DAYS', '5 days'), ('6 DAYS', '6 days')], max_length=6, verbose_name='Workout available days')),
                ('daily_spend', models.CharField(choices=[('LESS THAN 100 BUCKS', 'Less than 100 bucks'), ('100-150 BUCKS', '100-150 bucks'), ('150-200 BUCKS', '150-200 bucks'), ('MORE THAN 200 BUCKS', 'More then 200 bucks')], max_length=20, verbose_name='Daily spend')),
                ('measure_scale', models.CharField(choices=[('I DO HAVE', 'I do have'), ('I DO NOT HAVE', 'I do not have'), ('NO, BUT I WILL', 'No, but i will')], max_length=15, verbose_name='Having measurement scale')),
                ('before_nutrition', models.TextField(verbose_name='Previous Nutrition')),
                ('injuries', models.TextField(verbose_name='Injuries')),
                ('previous_gym', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Previous gym')),
                ('another_sports', models.TextField(blank=True, null=True, verbose_name='Another Sports')),
                ('habits', models.TextField(verbose_name='Any Habits')),
                ('confidence', models.CharField(choices=[('ABSOLUTELY', 'Absolutely'), ('MAYBE', 'Maybe'), ('NO', 'No')], max_length=10, verbose_name='Confidence')),
                ('comeback', models.CharField(choices=[('ABSOLUTELY', 'Absolutely'), ('NOT SURE', 'Not sure')], max_length=10, verbose_name='Comeback')),
                ('hear_about_us', models.CharField(choices=[('A FRIEND', 'A friend'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'Tiktok'), ('OTHER', 'Other')], max_length=10, verbose_name='Hear about us')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('FAT LOSS', 'Fat loss'), ('INCREASE MUSCLE MASS', 'Increase muscle mass'), ('INCREASE STRENTH', 'Increase strenth'), ('INCREASE ENDURANCE', 'Increase endurance'), ('TRAIN FOR FUNCTIONALITY', 'Train for functionality'), ('HAVING FUN', 'Having fun'), ('POST REHABILITATION STRENTH', 'Post rehabilitation strenth')], max_length=30, verbose_name='Fitness Goal')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_goals', to='members.basicinfo')),
            ],
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_governorate', to='members.governorate'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='images')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to='members.basicinfo')),
            ],
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='routine_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_routine_details', to='members.routinedetails'),
        ),
    ]
