# Generated by Django 5.2.5 on 2025-10-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='IS Activated'),
        ),
    ]
