# Generated by Django 5.2.6 on 2026-07-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='hear_about_us',
        ),
        migrations.CreateModel(
            name='HearAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('A FRIEND', 'A friend'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'Tiktok'), ('OTHER', 'Other')], max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hear_about_us', to='members.member')),
            ],
        ),
    ]
