# Generated by Django 5.2.6 on 2026-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_hear_about_us_hearaboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5, verbose_name='Preferred Language'),
        ),
    ]
